apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  description: Fancia application workloads
  sourceRepos:
    - "*"
  destinations:
    - namespace: "*"
      server: {{ .Values.clusterServer | quote }}
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
