apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aws-privateca-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - {{ include "argocd.finalizer" . }}
spec:
  project: platform
  source:
    repoURL: {{ .Values.charts.awsPrivateCaIssuer.repo | quote }}
    chart: {{ .Values.charts.awsPrivateCaIssuer.name | quote }}
    targetRevision: {{ .Values.charts.awsPrivateCaIssuer.version | quote }}
  destination:
    server: {{ .Values.clusterServer | quote }}
    namespace: cert-manager
  syncPolicy:
    {{ include "argocd.automatedSyncPolicy" . | nindent 4 }}
    syncOptions:
      - ServerSideApply=true
