apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-dns
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  finalizers:
    - {{ include "argocd.finalizer" . }}
spec:
  project: platform
  sources:
    - repoURL: {{ required "helmRepoUrl is required" .Values.helmRepoUrl | quote }}
      targetRevision: {{ .Values.targetRevision | quote }}
      ref: values
    - repoURL: {{ .Values.charts.externalDns.repo | quote }}
      chart: {{ .Values.charts.externalDns.name | quote }}
      targetRevision: {{ .Values.charts.externalDns.version | quote }}
      helm:
        valueFiles:
          - $values/platform-values/external-dns/values.yaml
          - $values/platform-values/external-dns/{{ include "argocd.dynamicValuesFile" . }}
  destination:
    server: {{ .Values.clusterServer | quote }}
    namespace: external-dns
  syncPolicy:
    {{ include "argocd.automatedSyncPolicy" . | nindent 4 }}
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
