version: 0.2
phases:
  install:
    commands:
      - curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
      - chmod +x kubectl
      - mv kubectl /usr/local/bin/kubectl
      - curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      - pip install pyyaml
  pre_build:
    commands:
      - aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
  build:
    commands:
      - cp $CODEBUILD_SRC_DIR_tf_apply_output/tf_outputs.json .
      - python3 values-gen.py --out-dir=main-chart
      - cat main-chart/values.json
      - export VPC_ID=$(jq -r '.vpcId' main-chart/values.json)
      - echo VPC_ID=$VPC_ID
      - helm repo add external-secrets https://charts.external-secrets.io
      - helm repo add eks https://aws.github.io/eks-charts
      - helm repo add awspca https://cert-manager.github.io/aws-privateca-issuer
      - helm repo update
      - helm upgrade --install external-secrets external-secrets/external-secrets --namespace $PROJECT_NAME --set installCRDs=true
      - |
        helm upgrade --install aws-load-balancer-controller eks/aws-load-balancer-controller \
          --namespace kube-system \
          --create-namespace \
          --set clusterName=$EKS_CLUSTER_NAME \
          --set region=$AWS_REGION \
          --set vpcId=$VPC_ID \
          --set serviceAccount.create=true \
          --set serviceAccount.name=aws-load-balancer-controller \
          --set serviceAccount.annotations."eks\\.amazonaws\\.com/role-arn"=arn:aws:iam::$AWS_ACCOUNT_ID:role/$ENVIRONMENT-$PROJECT_NAME-alb-controller-role \
          --set serviceMutatorWebhookConfig.failurePolicy=Ignore
      - echo Installing certifcate related helm charts...
      - helm upgrade --install aws-privateca-issuer awspca/aws-privateca-issuer --namespace $PROJECT_NAME
      - echo Starting 5-minute sleep to wait for cert-manager and aws-privateca-issuer to be ready...
      - sleep 300
      - helm upgrade --install $PROJECT_NAME ./main-chart --namespace $PROJECT_NAME
