import argparse
import json
import os
from pathlib import Path
from typing import Dict, List

import yaml

GENERATED_HEADER = "# Generated by values-gen.py — do not edit manually.\n"

INFRA_KEYS = (
    "projectName",
    "awsAccountId",
    "awsRegion",
    "domainName",
    "email",
    "vpcId",
    "acmCertificateArn",
    "privateHostedZoneId",
    "publicHostedZoneId",
)

PLATFORM_CHARTS = (
    "aws-load-balancer-controller",
    "cert-manager",
    "external-dns",
    "aws-ebs-csi-driver",
    "keda",
    "loki",
    "alloy",
)


def camel_to_snake(name: str) -> str:
    out = []
    for char in name:
        if char.isupper() and out:
            out.append("_")
        out.append(char.lower())
    return "".join(out)


def camel_to_upper_snake(name: str) -> str:
    out = []
    for char in name:
        if char.isupper() and out:
            out.append("_")
        out.append(char.upper())
    return "".join(out)


def load_tf_outputs(path: Path) -> dict:
    try:
        with open(path, encoding="utf-8") as handle:
            payload = json.load(handle)
    except FileNotFoundError:
        print(f"Error: Terraform outputs file not found at {path}")
        raise SystemExit(1) from None
    except json.JSONDecodeError:
        print(f"Error: could not decode JSON from {path}")
        raise SystemExit(1) from None

    environment = os.environ["ENVIRONMENT"]
    try:
        return payload[environment]["value"]
    except KeyError:
        print(f"Error: no Terraform outputs found for environment: {environment}")
        raise SystemExit(1) from None


def write_yaml(path: Path, data: dict) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as handle:
        handle.write(GENERATED_HEADER)
        yaml.dump(data, handle, default_flow_style=False)
    print(f"Generated {path}")


def resolve_infra_values(tf_outputs: dict) -> dict:
    values = {"environment": os.environ["ENVIRONMENT"]}
    for key in INFRA_KEYS:
        env_key = camel_to_upper_snake(key)
        if env_key in os.environ:
            values[key] = os.environ[env_key]
            continue
        snake_key = camel_to_snake(key)
        if snake_key in tf_outputs:
            values[key] = tf_outputs[snake_key]

    project_name = os.environ["PROJECT_NAME"]
    values["projectName"] = values.get("projectName") or project_name
    values["awsRegion"] = values.get("awsRegion") or os.environ.get("AWS_REGION", "eu-west-2")
    values["awsAccountId"] = values.get("awsAccountId") or tf_outputs.get("aws_account_id")
    return values


def pod_role_arn(account_id: str, namespace: str) -> str:
    return f"arn:aws:iam::{account_id}:role/{namespace}-pod-role"


def alb_role_arn(account_id: str, namespace: str) -> str:
    return f"arn:aws:iam::{account_id}:role/{namespace}-alb-controller-role"


def irsa_annotation(role_arn: str) -> dict:
    return {"eks.amazonaws.com/role-arn": role_arn}


def repositories_from_tf(tf_outputs: dict) -> List[dict]:
    rds_map = tf_outputs.get("rds_secret_name_map")
    if not isinstance(rds_map, dict):
        print("Warning: rds_secret_name_map not found or not a map in tf_outputs.")
        return []

    return [
        {
            "name": name,
            "databaseName": repo["databaseName"],
            "databaseSecretName": repo["databaseSecretName"],
        }
        for name, repo in rds_map.items()
    ]


def secrets_from_tf(tf_outputs: dict, namespace: str) -> List[dict]:
    creds_map = tf_outputs.get("credentials_name_map")
    if not isinstance(creds_map, dict):
        print("Warning: credentials_name_map not found or not a map in tf_outputs.")
        return []

    return [
        {
            "name": secret_name,
            "secretName": secret["secretName"],
            "namespace": secret.get("namespace", namespace),
        }
        for secret_name, secret in creds_map.items()
    ]


def main_chart_dynamic_values(values: dict, namespace: str, project_name: str) -> dict:
    account_id = values["awsAccountId"]
    return {
        "environment": values["environment"],
        "projectName": values["projectName"],
        "domainName": values["domainName"],
        "email": values.get("email"),
        "awsAccountId": account_id,
        "awsRegion": values["awsRegion"],
        "vpcId": values.get("vpcId"),
        "acmCertificateArn": values.get("acmCertificateArn"),
        "privateHostedZoneId": values.get("privateHostedZoneId"),
        "publicHostedZoneId": values.get("publicHostedZoneId"),
        "serviceAccount": {
            "create": True,
            "name": f"{project_name}-sa",
            "annotations": irsa_annotation(pod_role_arn(account_id, namespace)),
        },
        "repositories": values["repositories"],
        "secrets": values["secrets"],
    }


def platform_dynamic_values(values: dict, namespace: str, cluster_name: str) -> Dict[str, dict]:
    account_id = values["awsAccountId"]
    pod_irsa = irsa_annotation(pod_role_arn(account_id, namespace))
    alb_irsa = irsa_annotation(alb_role_arn(account_id, namespace))

    return {
        "aws-load-balancer-controller": {
            "clusterName": cluster_name,
            "vpcId": values["vpcId"],
            "serviceAccount": {"annotations": alb_irsa},
        },
        "cert-manager": {
            "serviceAccount": {"annotations": pod_irsa},
        },
        "external-dns": {
            "aws": {"region": values["awsRegion"]},
            "txtOwnerId": values.get("privateHostedZoneId", ""),
            "domainFilters": [values["domainName"]],
            "serviceAccount": {"annotations": pod_irsa},
        },
        "aws-ebs-csi-driver": {
            "controller": {"serviceAccount": {"annotations": pod_irsa}},
        },
        "keda": {
            "serviceAccount": {"annotations": pod_irsa},
        },
        "loki": {
            "serviceAccount": {"annotations": pod_irsa},
        },
        "alloy": {
            "serviceAccount": {"annotations": pod_irsa},
        },
    }


def argocd_dynamic_values(
    environment: str,
    project_name: str,
    namespace: str,
    helm_repo_url: str,
) -> dict:
    return {
        "environment": environment,
        "projectName": project_name,
        "namespace": namespace,
        "helmRepoUrl": helm_repo_url,
    }


def argocd_server_dynamic_values(domain_name: str) -> dict:
    host = f"argocd.{domain_name}"
    return {
        "server": {
            "ingress": {
                "hosts": [host],
            }
        },
        "global": {
            "domain": host,
        },
    }


def helm_repo_url(project_name: str) -> str:
    if url := os.environ.get("HELM_REPO_URL"):
        return url
    github_username = os.environ.get("GITHUB_USERNAME")
    if github_username:
        return f"https://github.com/{github_username}/{project_name}-helm"
    print("Warning: HELM_REPO_URL and GITHUB_USERNAME not set; argocd values will be incomplete.")
    return ""


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Generate dynamic Helm values from Terraform outputs."
    )
    parser.add_argument(
        "--var-file",
        type=Path,
        default=Path("tf_outputs.json"),
        help="Path to tf_outputs.json",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("."),
        help="Repository root for generated files",
    )
    args = parser.parse_args()

    if not args.var_file.is_file():
        print(f"Error: provided path does not exist: {args.var_file}")
        raise SystemExit(1)

    for var in ("ENVIRONMENT", "PROJECT_NAME"):
        if not os.environ.get(var):
            print(f"Error: {var} environment variable is not set.")
            raise SystemExit(1)

    project_name = os.environ["PROJECT_NAME"]
    environment = os.environ["ENVIRONMENT"]
    namespace = f"{project_name}-{environment}"
    cluster_name = os.environ.get("EKS_CLUSTER_NAME", f"{namespace}-eks")
    dynamic_file = f"values-{environment}.yaml"

    tf_outputs = load_tf_outputs(args.var_file)
    values = resolve_infra_values(tf_outputs)
    values["repositories"] = repositories_from_tf(tf_outputs)
    values["secrets"] = secrets_from_tf(tf_outputs, namespace)

    repo_root = args.out_dir
    write_yaml(
        repo_root / "main-chart" / dynamic_file,
        main_chart_dynamic_values(values, namespace, project_name),
    )

    for chart in PLATFORM_CHARTS:
        write_yaml(
            repo_root / "platform-values" / chart / dynamic_file,
            platform_dynamic_values(values, namespace, cluster_name)[chart],
        )

    write_yaml(
        repo_root / "argocd" / dynamic_file,
        argocd_dynamic_values(
            environment,
            project_name,
            namespace,
            helm_repo_url(project_name),
        ),
    )

    write_yaml(
        repo_root / f"argocd-values-{environment}.yaml",
        argocd_server_dynamic_values(values["domainName"]),
    )

    print("Dynamic values generation completed.")


if __name__ == "__main__":
    main()
