apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAClusterIssuer
metadata:
  name: aws-pca-clusterissuer
spec:
  arn: {{ $.Values.privateCaArn }}
  region: {{ $.Values.awsRegion }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $.Values.environment }}-{{ $.Values.projectName }}-tls-cert
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
spec:
  secretName: {{ $.Values.environment }}-{{ $.Values.projectName }}-tls
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
    - {{ $.Values.domainName }}
  issuerRef:
    name: aws-pca-clusterissuer
    kind: AWSPCAClusterIssuer
    group: awspca.cert-manager.io
