apiVersion: awspca.cert-manager.io/v1beta1
kind: AWSPCAClusterIssuer
metadata:
  name: aws-pca-clusterissuer
spec:
  arn: {{ $.Values.privateCaArn }}
  region: {{ $.Values.region }}

---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: aws-load-balancer-webhook-cert
  namespace: kube-system
  annotations:
    cert-manager.io/inject-ca-from: kube-system/aws-load-balancer-webhook-cert
    cert-manager.io/issuer: aws-pca-clusterissuer
spec:
  secretName: aws-load-balancer-webhook-tls
  duration: 2160h
  renewBefore: 360h
  isCA: false
  privateKey:
    algorithm: RSA
    size: 2048
  dnsNames:
    - aws-load-balancer-webhook-service.kube-system.svc
    - aws-load-balancer-webhook-service.kube-system.svc.cluster.local
  issuerRef:
    name: aws-pca-clusterissuer
    kind: AWSPCAClusterIssuer
    group: awspca.cert-manager.io
