{{- range $repo := $.Values.repositories  }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $repo.name }}-database
  namespace: {{ $.Release.Namespace }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: {{ $repo.name }}-database
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
         DATABASE_USERNAME: "{{ `{{ .username }}` }}"
         DATABASE_PASSWORD: "{{ `{{ .password }}` }}"
  dataFrom:
  - extract:
      key: {{ $repo.databaseSecretName }}
{{- end }}