{{- range $.Values.repositories  }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-database
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: {{ $.Values.environment }}-{{ .name }}-database
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
         DATABASE_USERNAME: "{{ `{{ .username }}` }}"
         DATABASE_PASSWORD: "{{ `{{ .password }}` }}"
  dataFrom:
  - extract:
      key: {{ .databaseSecretName }}
{{- end }}