apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gp3
provisioner: ebs.csi.eks.amazonaws.com
parameters:
  type: gp3                  
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
---

apiVersion: kafka.strimzi.io/v1
kind: KafkaNodePool
metadata:
  name: {{ $.Values.projectName }}-{{ $.Values.environment }}-dual-role
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
  labels:
    strimzi.io/cluster: {{ $.Values.projectName }}-{{ $.Values.environment }}-kafka
spec:
  template:
    pod:
      nodeSelector:
        eks.amazonaws.com/compute-type: auto
  replicas: 1
  roles:
    - controller
    - broker
  storage:
    type: jbod
    volumes:
      - id: 0
        type: persistent-claim
        size: 1Gi
        class: gp3
        kraftMetadata: shared
---

apiVersion: kafka.strimzi.io/v1
kind: Kafka
metadata:
  name: {{ $.Values.projectName }}-{{ $.Values.environment }}-kafka
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
  annotations:
    strimzi.io/node-pools: enabled
spec:
  kafka:
    version: 4.2.0
    metadataVersion: 4.2-IV1
    listeners:
      - name: plain
        port: 9092
        type: internal
        tls: false
      - name: tls
        port: 9093
        type: internal
        tls: true
      - name: external
        port: 9094
        type: loadbalancer
        tls: true
        configuration:
          loadbalancer:
            class: aws          
            useServiceDnsDomain: true
    config:
      offsets.topic.replication.factor: 1
      transaction.state.log.replication.factor: 1
      transaction.state.log.min.isr: 1
      default.replication.factor: 1
      min.insync.replicas: 1
  entityOperator:
    topicOperator: {}
    userOperator: {}