apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: monitoring
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: loki