{{- $sa := .Values.serviceAccount | default dict -}}
{{- $saName := $sa.name | default (printf "%s-sa" .Values.projectName) -}}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: {{ $.Release.Namespace }}
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: {{ .Values.awsRegion }}
      auth:
        jwt:
          serviceAccountRef:
            name: {{ $saName | quote }}