apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  namespace: {{ $.Values.projectName }}
  name: aws-secrets
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: {{ $.Values.projectName }}-sa