{{- range $.Values.repositories  }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .name }}
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
  labels:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Values.projectName }}-{{ $.Values.environment }}
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/part-of: {{ $.Values.projectName }}
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: {{ .port }}
      targetPort: {{ .port | default 8080 }}
  selector:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Values.projectName }}-{{ $.Values.environment }}
{{- end }}