{{- range $.Values.repositories  }}
{{- if eq .name "user" }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-bucket
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: {{ $.Values.environment }}-{{ .name }}-bucket
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ $.Values.environment }}/{{ $.Values.projectName }}-backend-{{ .name }}/s3
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ .name }}-smtp
  namespace: {{ $.Values.projectName }}-{{ $.Values.environment }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: SecretStore
  target:
    name: {{ $.Values.environment }}-{{ .name }}-smtp
    creationPolicy: Owner
  dataFrom:
  - extract:
      key: {{ $.Values.environment }}/{{ $.Values.projectName }}-backend-{{ .name }}/smtp
{{- end }}
{{- end }}